# Basic Information 
title: Yongtai Yin 殷永泰
position: Ph.D. Student
affiliation: Chinese University of Hong Kong
email: ytyin (at) link.cuhk.edu.hk

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: yongtai yin, ytyin, yin yongtai, yongtaiyin, yinyongtai
description: Yongtai Yin's Homepage.
canonical: https://yongtai-yin.github.io/

# The option is used to show the last update time.
enable_last_update: true

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=hNvpv2kAAAAJ&hl
cv_link: assets/files/curriculum_vitae.pdf
# github_link: https://github.com/
linkedin: https://www.linkedin.com/in/yongtai-yin-1b434b2a9
# twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: R5uEk2mKpcemxfezaBks5C2S87s5YN2gzMVmMHHKpTU

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
